version: '3.8'
services:
  web:
    image: ${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${DOCKER_TAG}
    container_name: web_service
    ports:
      - "8082:8080"
    restart: on-failure
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health/" ]
      interval: 20s
      timeout: 10s
      retries: 10
      start_period: 5s